export const commonExercises = [
    // Chest Exercises
    "Bench Press",
    "Incline Bench Press",
    "Decline Bench Press",
    "Chest Fly",
    "Incline Chest Fly",
    "Decline Chest Fly",
    "Push Up",
    "Wide Push Up",
    "Diamond Push Up",
    "Chest Dip",
    "Machine Chest Press",
    "Pec Deck Machine",
    "Cable Crossover",
    "Smith Machine Bench Press",

    // Back Exercises
    "Pull Up",
    "Wide Grip Pull Up",
    "Close Grip Pull Up",
    "Chin Up",
    "Lat Pulldown",
    "Close Grip Lat Pulldown",
    "Reverse Grip Lat Pulldown",
    "Bent Over Row",
    "Pendlay Row",
    "Single Arm Dumbbell Row",
    "T-Bar Row",
    "Seated Cable Row",
    "Inverted Row",
    "Deadlift",
    "Romanian Deadlift",
    "Sumo Deadlift",
    "Machine Row",
    "Machine Lat Pulldown",
    "Machine Seated Row",

    // Shoulder Exercises
    "Shoulder Press",
    "Arnold Press",
    "Seated Dumbbell Press",
    "Standing Barbell Press",
    "Lateral Raise",
    "Single Arm Lateral Raise",
    "Front Raise",
    "Plate Front Raise",
    "Reverse Fly",
    "Cable Reverse Fly",
    "Upright Row",
    "Dumbbell Upright Row",
    "Shrugs",
    "Barbell Shrugs",
    "Dumbbell Shrugs",
    "Machine Shoulder Press",
    "Cable Lateral Raise",
    "Cable Front Raise",

    // Bicep Exercises
    "Bicep Curl",
    "Hammer Curl",
    "Concentration Curl",
    "Preacher Curl",
    "Cable Curl",
    "Incline Dumbbell Curl",
    "Spider Curl",
    "EZ Bar Curl",
    "Reverse Curl",
    "Machine Bicep Curl",
    "Cable Hammer Curl",
    "Drag Curl",

    // Tricep Exercises
    "Tricep Dip",
    "Bench Dip",
    "Tricep Pushdown",
    "Reverse Grip Tricep Pushdown",
    "Skull Crusher",
    "Overhead Tricep Extension",
    "Single Arm Tricep Extension",
    "Tricep Kickback",
    "Close Grip Bench Press",
    "Machine Tricep Extension",
    "Cable Overhead Tricep Extension",
    "Rope Tricep Pushdown",

    // Leg Exercises
    "Squat",
    "Front Squat",
    "Back Squat",
    "Sumo Squat",
    "Goblet Squat",
    "Lunge",
    "Walking Lunge",
    "Reverse Lunge",
    "Side Lunge",
    "Bulgarian Split Squat",
    "Leg Press",
    "Single Leg Press",
    "Leg Extension",
    "Leg Curl",
    "Seated Leg Curl",
    "Standing Leg Curl",
    "Romanian Deadlift",
    "Calf Raise",
    "Seated Calf Raise",
    "Standing Calf Raise",
    "Glute Bridge",
    "Single Leg Glute Bridge",
    "Hip Thrust",
    "Machine Squat",
    "Hack Squat",
    "Smith Machine Squat",
    "Sissy Squat",
    "Leg Adductor",
    "Leg Abductor",
    "Donkey Calf Raise",
    "Cable Kickback",
    "Cable Pull Through",
    "Sled Push",
    "Sled Pull",

    // Core Exercises
    "Sit Up",
    "Crunch",
    "Reverse Crunch",
    "Leg Raise",
    "Hanging Leg Raise",
    "Plank",
    "Side Plank",
    "Russian Twist",
    "Bicycle Crunch",
    "Mountain Climber",
    "Ab Wheel Rollout",
    "V-Up",
    "Flutter Kick",
    "Cable Woodchopper",
    "Cable Twist",
    "Decline Sit Up",
    "Cable Crunch",
    "Machine Crunch",
    "Hanging Knee Raise",
    "Medicine Ball Slam",

    // Cardio Exercises
    "Running",
    "Sprinting",
    "Cycling",
    "Jump Rope",
    "Elliptical",
    "Rowing",
    "Stair Climber",
    "High Intensity Interval Training (HIIT)",
    "Box Jump",
    "Battle Ropes",
    "Treadmill Sprints",
    "Assault Bike",
    "Swimming",

    // Full Body Exercises
    "Burpee",
    "Kettlebell Swing",
    "Clean and Jerk",
    "Snatch",
    "Medicine Ball Slam",
    "Thruster",
    "Turkish Get-Up",
    "Dumbbell Clean",
    "Dumbbell Snatch",
    "Man Maker",

    // Compound Movements
    "Squat",
    "Deadlift",
    "Bench Press",
    "Overhead Press",
    "Pull Up",
    "Dip",

    // Isolation Movements
    "Bicep Curl",
    "Tricep Extension",
    "Leg Extension",
    "Leg Curl",
    "Calf Raise",
    "Lateral Raise",
    "Front Raise",
    "Concentration Curl",
    "Tricep Kickback",
    "Hammer Curl",

    // Mobility and Flexibility
    "Foam Rolling",
    "Dynamic Stretching",
    "Static Stretching",
    "Yoga Poses",
    "Pilates Movements",
    "Hip Flexor Stretch",
    "Hamstring Stretch",
    "Quadriceps Stretch",
    "Shoulder Stretch",
    "Thoracic Spine Stretch",
    "Cat-Cow Stretch",
    "Child's Pose",
    "Pigeon Pose",

    // Functional Movements
    "Farmer's Walk",
    "Sled Push",
    "Sled Pull",
    "Battle Ropes",
    "Box Jump",
    "Medicine Ball Throw",
    "Agility Ladder Drills",
    "Bear Crawl",
    "Sandbag Clean",
    "Tire Flip",
    "Atlas Stone Lift",
    "Sled Drag",
    "Log Press",

    // Other Exercises
    "Landmine Press",
    "Landmine Row",
    "Face Pull",
    "Pistol Squat",
    "Windmill",
    "Single Arm Snatch",
    "Weighted Carries",
    "Overhead Carries",
    "Lateral Shuffle",
    "Step Up",
    "Sled Row",
    "Suitcase Carry",
    "Yoke Carry"
];
